---
title: "Question 2 Feature selection"
author: "Anouk Dimbeanu"
date: "2025-03-24"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
library(caret)
library(MASS) 
url <- "https://raw.githubusercontent.com/emmaamitchyy/BIOL432_Gr3_Final/refs/heads/main/Data_Input/RawData.csv"
df <- read.csv(url)

```

```{r}
df$Age <- as.numeric(df$Age)
df$CT <- as.numeric(df$CT)
df$Age[is.na(df$Age)] <- mean(df$Age, na.rm = TRUE) 
head(df)

```

## Change the characters to numeric values

```{r}
dat <- clean_data %>%
  mutate(across(c(where(is.character), -c(Sample.Name, Batch.Number, Class.name, Sex, CT, Age)), as.numeric)) %>%
  mutate(across(where(is.numeric), ~ replace_na(., 0))) 
```


## Rearrange dataset 

```{r}
dat <- as_tibble(dat) 
dat <- dat[, c("Sample.Name", "Sex", "Age", "CT", setdiff(names(dat), c("Sample.Name", "Sex", "Age", "CT")))]
head(dat)
```

## Feature selection for only COVID-19


```{r}
respDat <- dat %>% 
  dplyr::select(1:6)
Features <- dat %>% 
  dplyr::select(-c(1:6))
table(respDat$Class.name)
```

## Scaling

```{R}
Scaled<-Features %>%mutate_all(scale)
```


## Find missing data

```{r}
Scaled %>%
  select_if(function(x) any(is.na(x))) %>%
  names()
```
 
 We only have to change Trp

```{r}
ScalComp <- Scaled %>% 
  mutate(Trp = ifelse(is.na(Trp), 0, Trp))
```


## Dimension reduction

```{r}
dim(ScalComp)
```

## PCA

```{r}
PCA <- princomp(ScalComp)
summary(PCA)
```

## Feature selection 

```{r}
FeatureSel <- ScalComp %>%
  mutate(Class.name = dat$Class.name) %>%
  pivot_longer(cols = -Class.name,
               names_to = "metabolite",
               values_to = "CONC")
str(FeatureSel) 
```


```{r}
heatmapdata <- ScalComp %>% 
  mutate(Class.name = dat$Class.name) %>% 
  filter(Class.name %in% c("COVID19"))

```